# Generated by Django 3.2.3 on 2021-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsyncTaskDemo', '0008_alter_images_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
